import { Booking, BookingStatus } from '@/components/admin/calendar/types';
export declare const getBookings: (userId: string) => Promise<import("@supabase/postgrest-js").PostgrestSingleResponse<{
    assigned_to: string | null;
    created_at: string;
    customer_address: string;
    customer_email: string;
    customer_name: string;
    customer_phone: string;
    delivery_failure_reason: string | null;
    end_date: string;
    id: string;
    start_date: string;
    status: string;
    total_amount: number;
    updated_at: string;
}[]>>;
export declare const insertBooking: (booking: Omit<Booking, "id">) => Promise<import("@supabase/postgrest-js").PostgrestSingleResponse<{
    assigned_to: string | null;
    created_at: string;
    customer_address: string;
    customer_email: string;
    customer_name: string;
    customer_phone: string;
    delivery_failure_reason: string | null;
    end_date: string;
    id: string;
    start_date: string;
    status: string;
    total_amount: number;
    updated_at: string;
}[]>>;
export declare const updateBookingStatus: (bookingId: string, newStatus: BookingStatus, oldStatus?: BookingStatus) => Promise<{
    assigned_to: string | null;
    created_at: string;
    customer_address: string;
    customer_email: string;
    customer_name: string;
    customer_phone: string;
    delivery_failure_reason: string | null;
    end_date: string;
    id: string;
    start_date: string;
    status: string;
    total_amount: number;
    updated_at: string;
    booking_items: {
        booking_id: string;
        created_at: string;
        equipment_id: string;
        equipment_name: string;
        equipment_price: number;
        id: string;
        quantity: number;
        subtotal: number;
        equipment: {
            availability: boolean;
            availability_status: string | null;
            category: string | null;
            category_id: string | null;
            created_at: string;
            description: string | null;
            featured: boolean;
            id: string;
            images: string[] | null;
            name: string;
            price_per_day: number;
            sort_order: number | null;
            stock_quantity: number;
            sub_category: string | null;
            sub_category_id: string | null;
            updated_at: string;
        } | null;
    }[];
}>;
