// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abofxrgdxfzrhjbvhdkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib2Z4cmdkeGZ6cmhqYnZoZGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTE5OTYsImV4cCI6MjA2NDA4Nzk5Nn0.n3j6qicmmHvCOLWDUClCfyir2StsOMmyNWedghySo-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);