// This file is automatically generated. Do not edit it directly.
import { createClient as supabaseCreateClient } from '@supabase/supabase-js'; // Renamed import
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_PUBLIC_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = supabaseCreateClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
export { supabaseCreateClient as createClient }; // Export createClient
